name: Deploy to Azure App Service

on:
  push:
    branches: [ ai-azure-prod ]
  pull_request:
    branches: [ ai-azure-prod ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests (optional)
      run: |
        # Add your tests here
        python -c "import app; print('App imports successfully')"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      if: github.ref == 'refs/heads/ai-azure-prod'
      with:
        app-name: 'driverguardai'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
